### ISSUE TITLE
Feature Request: Ingress Definition vs Annotation

### ISSUE THREAD

**Issue by sfxworks** [itzg/mc-router#6]
This is a great binary. I want to actually see about converting it to ingress (minus the TLS options) since, overall, it fits the resource [networking.k8s.io/Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
). 

It could conform to an ingress class, point to a service based on the name. The mc-router binary would run in a controller watching for updates to that definition instead of via service annotation (which honestly looks very nice already)

**Comment by itzg** [comment]
I agree, it seems conceptually perfect as an Ingress; however, the kubernetes API specification so far only allows for `http` rules:

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#ingressrule-v1beta1-networking-k8s-io

and I have found in the past that there are outstanding feature requests for non-http rules to be allowed by the ingress resource.

Understandably, it will be tough for the Kubernetes SIGs to expand ingress beyond http rules though, because they currently map one for one to L7 routers in the managed cloud offerings, such as ELBs in AWS, and those L7 routers only support HTTP. L4 load balancers are intended for arbitrary TCP routing and the `type=LoadBalancer` on a `Service` kubernetes resource maps to those in the managed cloud solutions. That's actually how I currently deploy mc-router into a GKE cluster:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mc-router
spec:
  selector:
    app: mc-router
  ports:
    - port: 25565
  type: LoadBalancer
```

One more note when I went to search for "kubernetes ingress non-http", I found that nginx ingress (which I currently use) mentions some support for non-http services; however, it looks even more awkward with a need for a "shim" ConfigMap

https://kubernetes.github.io/ingress-nginx/user-guide/fcgi-services/

**Comment by sfxworks** [comment]
My thought was since the ingress spec `host` field just needs to fit the [RFC](https://tools.ietf.org/html/rfc3986) the ingress operator, which would be the mc-router, could read this definition just fine and apply a Minecraft routing rule to the service the ingress definition is referencing.

**Comment by sfxworks** [comment]
Eh, on second thought, that http map name would still be a bit misleading.

**Comment by itzg** [comment]
Yeah, anything is possible by having mc-router watching the ingress resource...but it would feel pretty hacky to overload the meaning of the spec entry like that.

**Comment by sfxworks** [comment]
Kubernetes 1.18 came out with the IngressClass resource https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class which allows for the custom declaration of values. Maybe something to watch, but closing my FR for now since I believe `http` in the Ingress resource may still be required.
